### ISSUE TITLE
Kratu is handling dates differently than AwRerpoting

### ISSUE THREAD

**Issue by gustavo-moreira** [googleads/aw-reporting#125]
When querying for an specific date in Kratu, it only return values for a single date if you specify the date and the next day:
/kratu?dateStart=20150328&dateEnd=20150328&__kratuTimestamp=1428355715748
This one doesn't bring any data, and should bring the data for: 20150328

/kratu?dateStart=20150328&dateEnd=20150329&__kratuTimestamp=1428355715748
This second one brings the data for: 20150328

It would help if the first one was inclusive, like in the rest of the project.

**Comment by gustavo-moreira** [comment]
Joel, I am assigning the Kratu issues to you, so you can decide what to do and who might be the best person to implement it, and not because i am expecting you to implement this.

Cheers.

**Comment by joeltoby** [comment]
This issue is caused by the start and end datetimes being offset by + 12 hours in the SQL query.  E.G:
2015-05-25 15:46:56 TRACE BasicBinder:84 - binding parameter [2] as [TIMESTAMP] - Thu Jan 01 12:00:00 GMT 2015
2015-05-25 15:46:56 TRACE BasicBinder:84 - binding parameter [3] as [TIMESTAMP] - Fri Jan 02 12:00:00 GMT 2015

The above values should have been:
Thu Jan 01 0:00:00 GMT 2015
Fri Jan 02 0:00:00 GMT 2015

**Comment by joeltoby** [comment]
Method DateUtil.parseDateTime is adding 12 hours to the returned value:

<code>return localDateTime.plusHours(12).toDateTime(DateTimeZone.UTC);</code>

I can't see any reason why this is needed, so I'm removing it for now.

**Comment by joeltoby** [comment]
Correction to the above MySQL `UPDATE`.  Please use the following to update your DB:

`mysql> update AW_Kratu set DAY = DATE_ADD(DAY, INTERVAL 12 hour) where HOUR(DAY) = 0;`
`mysql> update AW_Kratu set DAY = DATE_ADD(DAY, INTERVAL 11 hour) where HOUR(DAY) = 1;`
