### ISSUE TITLE
Upgrade to v201502

### ISSUE THREAD

**Issue by Timmeh74** [googleads/aw-reporting#140]
We are currently running v1.6.0 of AwReporting. For the migration to v201502 I have now tested v1.7.0 (current master) on a fresh database and compared the database schemas as suggested in http://googleadsdeveloper.blogspot.tw/2015/04/awreporting-upgraded-to-use-adwords-api.html . I have then changed the SQL statements in our own code accordingly to match the new field names.

When I now run v1.7.0 on my existing AwReports database, will the database fields be renamed automatically or do I have to setup a fresh database and re-import my reporting data to the new structure afterwards?

**Comment by gustavo-moreira** [comment]
Hi,

if you run the new version of AwReporting with the old database, it will create new columns for the fields that changed names, and leave the old columns in the tables. You will end up with with a column with the old name holding the values that were downloaded before the migration, and a new one with the values that were downloaded after the migration. The values will be null otherwise, so you will have to create a script to copy the values from the old columns to the new one, and update the table schema to remove the column with the old name.

Att.

**Comment by chenzhuo914** [comment]
Closing now since there's no follow-up questions. Feel free to reopen it when needed.
