### ISSUE TITLE
"Unknown column 'CONVERSIONS'..." 

### ISSUE THREAD

**Issue by robtro** [googleads/aw-reporting#158]
Did I miss a notice or something? 

I wasn't expecting a database schema update that changed things so drastically. (which broke almost everything that had any use of the 'conversions' field)

**Comment by chenzhuo914** [comment]
Hi Robtro, this was a tradeoff that we decide to take during v201502 migration, as we believe it's a long-term benefit to keep report fields and database columns in sync, especially when there were many fields got renamed so we did it in one go.

We published a blog post about this change, and provided instructions on how to migrate the database. Please see more details at http://googleadsdeveloper.blogspot.tw/2015/04/awreporting-upgraded-to-use-adwords-api.html

**Comment by robtro** [comment]
... what about AW_ReportKeyword being changed to AW_ReportKeywords ?

**Comment by chenzhuo914** [comment]
It's another decision during v201506 migration, as we want to enforce clear report_name -> table_name mapping. Since the report name is "Keywords Performance Report", the table name should use "...Keywords" instead of "...Keyword" (note that there's report name containing "Keyword" instead of "Keywords" as well). Again, it should help new users quickly figure out which table is for which report.

We tried to make such "breaking" changes during major version upgrades, and we understand it will break existing users like you, but the migration should not be so hard, and it's a one-time job. In the future we will try best to make it right in the first place, and avoid unnecessary changes.
