### ISSUE TITLE
Download AGE_RANGE_PERFORMANCE_REPORT and GENDER_PERFORMANCE_REPORT 

### ISSUE THREAD

**Issue by fernandacaroline2008** [googleads/aw-reporting#161]
AW-report does not download AGE_RANGE_PERFORMANCE_REPORT and GENDER_PERFORMANCE_REPORT. How solve this problem?

**Comment by chenzhuo914** [comment]
Hi fernandacaroline2008,

Sorry due to resource constraint we don't have plan to add more report types in AwReporting in near future. However, as an open source project, you can do that yourself! Basically you need to:
- Create a class in the report model package that contains all the fields available in the report you want to add. Remember to extend one of the available super classes, so you get a lot of fields that are common across reports.
- In your new class, add the CSV mapping annotations so the CSV parser can map between the field in the Report definition, the CSV file and the Java entity.
Add the report key to the class, also with an annotation.
- (optional) Create a unit test based on the other examples. The base unit test will check for DB mapping, and will require a CSV downloaded from the report API, to test the CSV mapping.
- Add the report definition to the properties file.
- Run the project and make sure the table was created, and the report is being downloaded. All the DB configuration is done automatically.

The best way to do it, is to take a look at the other classes available. It is a very straight forward process.

**Comment by gustavo-moreira** [comment]
The reports are now available.
