### ISSUE TITLE
AW_ReportKeyword,AW_ReportDisplayKeywordPerformance

### ISSUE THREAD

**Issue by gezimapi** [googleads/aw-reporting#175]
hi,
After the update version of aw-reporting in the tables AW_ReportKeyword, AW_ReportDisplayKeywordPerformance  i have nothing inserted . I have checked the aw-report-sample.properties file and it seems ok. can anyone tell me where is the problem.
thanks.

**Comment by chenzhuo914** [comment]
Hi gezimapi, this is the result of commit f4fddee54d6bbe39b9d21a01f8d1c53b918067f2: apply same naming convention for report classes.

Please check tables AW_ReportKeywords and AW_ReportDisplayKeyword respectively.

**Comment by gezimapi** [comment]
Sorry i dont understand , can u be more specific.

thanx.

**Comment by chenzhuo914** [comment]
Some database tables were renamed:
- old "AW_ReportKeyword" table was renamed to be "AW_ReportKeywords"
- old "AW_ReportDisplayKeywordPerformance" table was renamed to be "AW_ReportDisplayKeyword"

**Comment by gezimapi** [comment]
Yes i have in my database this new tables  but AW_ReportKeywords does not have the column KEYWORD_TEXT anymore , is this column in any new tables , because a need that.

**Comment by gustavo-moreira** [comment]
Hi, this column was removed from the API, because its value was duplicated from the Criteria column.
You can find the exact same information under the Criteria column in the report.

**Comment by gezimapi** [comment]
i checked and the Criteria column is always empty in both tables AW_ReportKeywords,AW_ReportDisplayKeyword. have did something wrong?

**Comment by chenzhuo914** [comment]
It works for me. Please double check that you have specified "Criteria" field for DISPLAY_KEYWORD_PERFORMANCE_REPORT and KEYWORDS_PERFORMANCE_REPORT in the configuration file (aw-report-sample.properties).

**Comment by gezimapi** [comment]
this are my 

KEYWORDS_PERFORMANCE_REPORT=ExternalCustomerId,Date,AccountDescriptiveName,Cost,Clicks,Impressions,Conversions,Ctr,AverageCpm,AverageCpc,AveragePosition,AccountCurrencyCode,Id,QualityScore,KeywordMatchType,KeywordText,DestinationUrl,AdGroupId,CampaignId,Status,IsNegative,CampaignName

DISPLAY_KEYWORD_PERFORMANCE_REPORT=ExternalCustomerId,Date,CampaignId,CampaignName,AdGroupId,AdGroupName,Id,Cost,Clicks,Impressions,Conversions,Ctr,AverageCpc,AverageCpm,DestinationUrl,KeywordText,IsNegative,Status

where can i add the criteria field?

thanx

**Comment by chenzhuo914** [comment]
Well, just append it in the list.

KEYWORDS_PERFORMANCE_REPORT=ExternalCustomerId,Date,AccountDescriptiveName,Cost,Clicks,Impressions,Conversions,Ctr,AverageCpm,AverageCpc,AveragePosition,AccountCurrencyCode,Id,QualityScore,KeywordMatchType,KeywordText,DestinationUrl,AdGroupId,CampaignId,Status,IsNegative,CampaignName**,Criteria**

DISPLAY_KEYWORD_PERFORMANCE_REPORT=ExternalCustomerId,Date,CampaignId,CampaignName,AdGroupId,AdGroupName,Id,Cost,Clicks,Impressions,Conversions,Ctr,AverageCpc,AverageCpm,DestinationUrl,KeywordText,IsNegative,Status**,Criteria**

In order to use this tool most effectively, you should understand the meaning of fields and reports, and specify them properly. :)

**Comment by gezimapi** [comment]
its ok thanx for the help.
