### ISSUE TITLE
How to identify auto bids?

### ISSUE THREAD

**Issue by muhlegg** [googleads/aw-reporting#185]
How can I determine if a bid i auto or "normal"? The docs says that the MAX_CPC should include the "auto:" indicator for auto bids but since the MAX_CPC is of type decimal it does not work for aw reporting data. Is there a specific aw reporting solution to this?

**Comment by chenzhuo914** [comment]
Hi muhlegg! You are right, it seems to be a bug in aw-reporting, when it returns "auto" or "--" the code will break. We should store the MAX_CPC as String type in the database. We will fix it soon. Thanks!

**Comment by chenzhuo914** [comment]
After a second look, it turns out this is by design.

Please check ModifiedCsvToBean.java, the processLine() method. For fileds with @MoneyField annotation, it will filter all non-digital characters, and covert the micro amount into normal money amount. So for auto bids, it will filter "auto: " and convert the digital value only.

It's arguable whether this behavior is the best choice, but we think it meets most users' intention: just operation MAX_CPC as a value, no matter if it's from auto bidding. If you must retain the "auto" indicator, please feel free to modify the source code and implement your only logic.

**Comment by muhlegg** [comment]
Ok. At least to us the auto info is important, and I guess its quite critical for everyone doing any kind of bid optimization.

One solution would be to extract the "auto" value and add som kind of "MAX_CPC_AUTO" flag to the database. At the moment we do not have the resources to make any source changes to this project so unfortunately thats not an option.

**Comment by chenzhuo914** [comment]
Another option is to change the maxCpc to be String type, and simply copy the data from report without any conversion. Then when you are reading data from the database, you have to: 1) check the "auto" information; 2) convert number values from micro amount to normal amount (i.e., divide by 1000000).

**Comment by muhlegg** [comment]
Yep. I still though think thats it's a bit strange that AwReporting is by design breaking the adwords api specs?

**Comment by chenzhuo914** [comment]
Hmm... I would say the design philosophy is to make it simple and general usage, and we think current behavior is a balance:
- simply storing the string value is not so useful, as users have to manually manipulate the value for own purposes
- many users would just regards this "CpcBid" field as monetary values, so we just hide the "auto" stuff there.

For sophisticated users like you, they have capability to customize this tool to implement own business logic. :)
