### ISSUE TITLE
 Problem with update the value daily budget

### ISSUE THREAD

**Issue by fernandacaroline2008** [googleads/aw-reporting#198]
There is a problem with the value daily budget. When the routine updates the AW_ReportCampaign table, the budget of the current campaign overwrites the value of the previous days. This change impacts on my comparison report between the client's budget and what was spent in the period (cost).

Thank You.

**Comment by chenzhuo914** [comment]
Because the daily budget (field "[Amount] (https://developers.google.com/adwords/api/docs/appendix/reports/budget-performance-report#amount)" in Campaign Performance Report) is an Attribute field, and according to the [doc] (https://developers.google.com/adwords/api/docs/appendix/reports#field-attributes):
> Attribute The field contains settings or other fixed data. The values returned will always reflect the **current** state of the account, ignoring the timespan of the report. The field is generally compatible with zero-impression reports.

If you need, you could:
* Avoid running aw-reporting of the same timespan at different times, so the budget data won't be overwritten; or
* Save the daily budget of each timespan into another place (just save once, don't overwrite on next run), and load from there if you need historical budget data.

**Comment by gustavo-moreira** [comment]
We will think about this one as a possible enhancement. Keeping the account history might be tricky depending on the use case.
