### ISSUE TITLE
Creating new reports not available..

### ISSUE THREAD

**Issue by c-arnab** [googleads/aw-reporting#221]
I was looking to create a new report 'Click Performance Report' not available currently with aw-reporting and found Chenzhuo914's answer here(https://github.com/googleads/aw-reporting/issues/161).

What I understood of it was to create a new java file in awreporting.model.entities package and add the variables defined there to aw-report-sample.properties file.

But when I started checking the classes in said package, I have got confused..

Account Performance Report is defined in ReportAccount.java and gets stored in AW_ReportAccount. 

It has a field named 'ACCOUNT_DESCRIPTIVE_NAME' which gets saved in db in column '`aw_reportaccount`.`ACCOUNT_DESCRIPTIVE_NAME`', but when I look for it in the class file, I can't find it.

Similar case is for `ACCOUNT_DESCRIPTIVE_NAME` in  URL Performance Report.

So, how are these values being picked up and stored in db?

Also, could you please explain how one would decide on fields present in setid() function.

This is a real nice project..
Thanks

**Comment by chenzhuo914** [comment]
The ReportAccount (for Account Performance Report) class inherits the ReportBase, which contains "AccountDescriptiveName" field.

We may lack some fields in various reports, but if you find you need to use any of them, please feel free to file an issue here, or just add the fields into corresponding class yourself.

Regarding setId(), it's responsible to generate RowIds in database, in a way that if you download the same report of the same time period again, it will generate same RowIds so that the data would be updated instead of duplicated. Basically it should concatenate the id of the report type (say, account id of the Account Performance Report) and ALL the segment fields.

We are making some effort to make up all the missing reports / fields together, which will cover Click Performance Report and the setId. No ETA yet, so if you need it urgently you can write code yourself.

**Comment by chenzhuo914** [comment]
Closing this bug, as there's no action needed for now.
