### ISSUE TITLE
AWReporting Call details report

### ISSUE THREAD

**Issue by daviptch** [googleads/aw-reporting#240]
Hi,

I am wondering how I can extract 'Call Details' data like the report in Google Adwords (http://take.ms/IcNq9) with AWReporting.

As far as I can see, this report might be the 'CALL_METRICS_CALL_DETAILS_REPORT' one, which seems not to be in AWReporting. If that's true, will it be implemented sometime?

Regards.

**Comment by chenzhuo914** [comment]
Hi daviptch,


You are right, currently AwReporting doesn't support all the [report types](https://developers.google.com/adwords/api/docs/appendix/reports), and [Call Metrics Call Details report](https://developers.google.com/adwords/api/docs/appendix/reports) is not there.

We are working to support full list of report types, but it may take some time due to other prioritization. If you cannot wait, you can always try to add this report type yourself. Just look at some existing report type (such as Account Performance Report) and try to do the similar logic for Call Metrics Call Details report.
