### ISSUE TITLE
Add Click Performance Report

### ISSUE THREAD

**Issue by draven72** [googleads/aw-reporting#244]
Hi

Are there any plans in the near future to include support for the Click Performance Report? I'm looking to extract the cost data from Adwords and match it with our Analytics data, but to do this I need map the cost with the GclID, which only appears in the Click Performance Report.

Thanks

Ben

**Comment by chenzhuo914** [comment]
Hi Ben,

We are having an effort to make up all the API supported report types, including Click Performance Report. But it may take a bit of time due to prioritization and code review process, so you may need to wait a few months.

If you cannot wait, please feel free to define the entity class for this report type in aw-reporting-model module, by referring to the entity class of some existing report type, such as [ReportAccount.java] (https://github.com/googleads/aw-reporting/blob/master/aw-reporting-model/src/main/java/com/google/api/ads/adwords/awreporting/model/entities/ReportAccount.java) for Account Performance Report.

**Comment by draven72** [comment]
Thanks Zhuo, do I just need to create a new entity file or are there some other files I need to update? I write my stuff in Clojure so I'm not that familiar with Java.

**Comment by chenzhuo914** [comment]
I think you just need to create a ReportClick.java entity class and (optionally) a unit test for it. Here's a summary of what you'll do:
1. Create a class in the report model package that contains all the fields available in the report you want to add. Remember to extend one of the available super classes, so you get a lot of fields that are common across reports.
2. In your new class, add the CSV mapping annotations so the CSV parser can map between the field in the Report definition, the CSV file and the Java entity.
3. Add the report key to the class, also with an annotation.
4. Create a unit test based on the other examples. The base unit test will check for DB mapping, and will require a CSV downloaded from the report API, to test the CSV mapping.
5. Add the report definition to the properties file.
6. Run the project and make sure the table was created, and the report is being downloaded.

**Comment by draven72** [comment]
Thanks, I'll give this a go.

**Comment by c-arnab** [comment]
@draven72 did this work.. would be great if you could share your experience and if it worked share the fork
