### ISSUE TITLE
aw-reporting-server

### ISSUE THREAD

**Issue by jideCreppy** [googleads/aw-reporting#245]
Hi, 

I use the aw-reporting platform for daily campaign reports  which inserts all data into a Mongo DB database.  While creating reports i realized that the "conversions" field present in Google ad words is missing. from what i understand it was available. Currently i have documents in Mongo with convertedClicks but no conversions field.

Any suggestions?

Cheers

**Comment by chenzhuo914** [comment]
Please check which fields you have specified to download in the properties file. There are quite a few fields related to conversions (such as "Conversions", "ConvertedClicks", "AllConversions") in various report types, please refer to the [documentation](https://developers.google.com/adwords/api/docs/appendix/reports/all-reports) to find which report type has which fields.

**Comment by jideCreppy** [comment]
Hi and many thanks for the speedy reply. I have some more information if this would help solve the issue i am having.  My current employers upgraded to both aw-reporting and aw-reporting-server v201603
We stopped getting conversions around September/November 2015.  Please see attached for the current and previous properties file used. The target report for us is the Account Performance report.

Many thanks!


[old.kratubackend.txt](https://github.com/googleads/aw-reporting/files/318020/old.kratubackend.txt)
[kratubackend_properties_current.txt](https://github.com/googleads/aw-reporting/files/318021/kratubackend_properties_current.txt)

**Comment by chenzhuo914** [comment]
Hi there, sorry for late reply. Unfortunately we don't have resource for supporting aw-reporting-server at the moment.

I did a quick check, and I guess the reason is that since v201509, the field "ConversionsManyPerClick" was renamed as "Conversions", with type change from "Long" to "Double". The type was changed in aw-reporting-model and aw-reporting modules, but was not changed in aw-reporting-server module.

Since this is open source, could you change all the Conversions related fields as BigDecimal type? Please let me know if it solves the problem.

**Comment by jideCreppy** [comment]
HI, Thanks for the response. I should have informed you that this is fixed now. From your previous response which was very helpful Conversions was added to the properties file and everything seems okay now. Thanks
