### ISSUE TITLE
Build Problem when the computer Clock Format isn't English

### ISSUE THREAD

**Issue by felipegoncalvesmarques** [googleads/aw-reporting#246]
When the computer Clock Format isn't "en", the build will fail because some test won't pass.
In the "TempleateStringsUtilTest.java", add/change the following lines:

20| import java.util.Locale;
33| private SimpleDateFormat format = new SimpleDateFormat("MMMMM yyyy", new Locale("en"));
34| private SimpleDateFormat abrieviatedFromat = new SimpleDateFormat("MMM yyyy", new Locale("en"));

**Comment by chenzhuo914** [comment]
Thanks for reporting!

Allison would you please solve it during code migration? Thanks~

**Comment by chenzhuo914** [comment]
After a second look, actually in this test it's using SimpleDateFormat's behavior to test DateTimeFormatter's behavior (in TemplateStringsUtil), and both should be using the system locale, so it shouldn't fail.

Anyway, we think it's not necessary, and will update DateTimeFormatter to use fixed Locale.US, and make this test to check against literal strings instead of SimpleDateFormat.format() results.

Please use whatever workaround you have now, and in next release the SimpleDateFormat will be removed and any problem will be solved.
