### ISSUE TITLE
AW_ReportAd HEADLINE,LINE1,LINE2,DISPLAY_URL are empty

### ISSUE THREAD

**Issue by gezimapi** [googleads/aw-reporting#251]
hi 

i need help in the table AW_ReportAd columns HEADLINE,LINE1,LINE2,DISPLAY_URL are empty this start from date 03/08/2016 in differnt accounts.

**Comment by fernandacaroline2008** [comment]
Hi, 

I have the same problem. I think that this is related with the new ads expanded. What do we do?

https://developers.google.com/adwords/api/docs/reference/v201607/AdGroupAdService.ExpandedTextAd

Thaks

**Comment by Timmeh74** [comment]
Hi!

This issue is indeed caused by expanded text ads, which use new fields on the AdPerformanceReport. You'll need to upgrade awReporting to use a current API version and add the new fields to your properties file. More information on which fields are used for expanded text ads are available at https://developers.google.com/adwords/api/docs/guides/expanded-text-ads#upgrade_tips

Keep in mind that as long as you still have standard text ads in your account, you'll have to download the "old" fields as well and your applications need to evaluate the AdType field (see URL above).

**Comment by chenzhuo914** [comment]
Tim is indeed right!

If there are ETA (Expanded Text Ads) in the report data, and you've added related fields in the properties file, the corresponding values will populate in those database columns.

**Comment by gezimapi** [comment]
Hi
Which are these field tha i should add in properties file for ETA

Thx

On Sep 19, 2016 5:40 AM, "Zhuo Chen" <notifications@github.com> wrote:

Tim is indeed right!

If there are ETA (Expanded Text Ads) in the report data, and you've added
related fields in the properties file, the corresponding values will
populate in those database columns.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/googleads/aw-reporting/issues/251#issuecomment-247906540>,
or mute the thread

**Comment by chenzhuo914** [comment]
You may want to look at [ReportAd](https://github.com/googleads/aw-reporting/blob/master/aw-reporting-model/src/main/java/com/google/api/ads/adwords/awreporting/model/entities/ReportAd.java) source code to figure out the corresponding report field names of those columns. :)

**Comment by fernandacaroline2008** [comment]
Hi, 

I inserted the colums headlinePart1,headlinePart2,line1,line2, path1, path2, in AD_PERFORMANCE_REPORT but I can't see the values in datbase. What do I do?

Thanks
