### ISSUE TITLE
Verbose/debug output on latest version

### ISSUE THREAD

**Issue by Timmeh74** [googleads/aw-reporting#253]
Hi!

I just upgraded to the current version of AwReporting using API v201607. Everything is running fine so far, but it seems that debug/verbose info (i.e. by the ReportServiceLogger) is now shown on screen when calling the script from the command line, even though I'm not specifying the _-debug_ or _-verbose_ options. The same info is also written to report.log where it belongs, but it would be helpful if it wouldn't show on screen. Is this a "bug" or is there a new option to get rid of the on-screen output?

**Comment by chenzhuo914** [comment]
Interesting, the [code logic](https://github.com/googleads/aw-reporting/blob/master/aw-reporting/src/main/java/com/google/api/ads/adwords/awreporting/AwReporting.java#L399) around "-debug" and "-verbose" has not been changed since long time ago. On my side, running without "-debug" and "-verbose" does not print debug messages on console.

Could you double check whether you are running with some other configurations that includes "-debug" and "-verbose"? Or do you have some local code change that always set debug log level? Otherwise you'll have to debug into the code to see what happens with the log level. Kingly let us know your findings.

Btw, we will be removing these two options in the future, and all the logs (file or console) granularities should be configured in the log4j / slf4j properties file.

**Comment by chenzhuo914** [comment]
Closing since there's no further discussion. Feel free to reopen it if you still have question.
