### ISSUE TITLE
AW_ReportKeywords 

### ISSUE THREAD

**Issue by gezimapi** [googleads/aw-reporting#256]
Some ACCOUNT_ID don't any record in the table  AW_ReportKeywords but have records in other table like AW_ReportAd.

in the aw-report-sample.properties im using:

KEYWORDS_PERFORMANCE_REPORT=ExternalCustomerId,Date,AccountDescriptiveName,Cost,Clicks,Impressions,ConvertedClicks,Ctr,AverageCpm,AverageCpc,AveragePosition,AccountCurrencyCode,Id,QualityScore,KeywordMatchType,Criteria,CriteriaDestinationUrl,AdGroupId,CampaignId,Status,IsNegative,CampaignName

AD_PERFORMANCE_REPORT=ExternalCustomerId,Date,AccountDescriptiveName,Cost,Clicks,Impressions,ConvertedClicks,Ctr,AverageCpm,AverageCpc,AveragePosition,AccountCurrencyCode,Id,DisplayUrl,Url,Headline,Description1,Description2,AdGroupId,CampaignId,Status,CreativeApprovalStatus,Description,HeadlinePart1,HeadlinePart2,LongHeadline,Path1,Path2,ShortHeadline

how can i fix this problem?

**Comment by chenzhuo914** [comment]
Hi gezimapi,


I understand your problem but have no idea why it's happening. Would you please narrow down the problem and provide a repro (with specific CID and date range for pulling Keywords Performance Report)?

In aw-reporting, both ReportKeywords (entity for persisting AW_ReportKeywords) and ReportAd (entity for persisting AW_ReportAd) inherit from ReportBase, which inherit from Report, which is responsible for storing ACCOUNT_ID into the database tables:
>   @Column(name = "ACCOUNT_ID")
>   @CsvField(value = "Customer ID", reportField = "ExternalCustomerId")
>   protected Long accountId;
So by right it should have problem on AW_ReportKeywords but not AW_ReportAd, and on some accounts only.

The only possibility I can think of is that for some accounts, the downloaded keywords performance reports don't contain value for ACCOUNT_ID, which could be a bug on AdWords API itself. But in order to confirm that, we need you to provide info for a minimal repro.


Thanks and regards,
Zhuo

**Comment by gezimapi** [comment]
hi Zhuo,
This is one of ACCOUNT_ID 5471232902

Thanks for the help

**Comment by chenzhuo914** [comment]
Hi gezimapi, I confirm that my AwReporting can successfully pull Keywords Performance Report data of CID 5471232902, during 20161001 to 20161031, using the KEYWORDS_PERFORMANCE_REPORT setting as in your properties file. It persists 1314 rows into the database.

I'm not sure what's wrong at your side (that causes AW_ReportKeywords is empty but AW_ReportAd has some data). Would you please run AwReporting with KEYWORDS_PERFORMANCE_REPORT only, turn on "-debug" switch, and check if there's any error message in console and log?

**Comment by gezimapi** [comment]
Hi zhuo chen

I have the version of aw-reporting and for now everything seems ok.

Thx for the help

**Comment by chenzhuo914** [comment]
Okay, thanks for letting me know it.
