### ISSUE TITLE
Setting up the aw-reporting-server

### ISSUE THREAD

**Issue by mitaky** [googleads/aw-reporting#262]
I am setting the server's document root to be "aw-reporting\aw-reporting-server\src\html"

However, to load the mcc information, it is making a request to a route called "/mcc", which doesn't exist anywhere.

Where exactly do I need to point my server, in order to use the out-of-the-box functionality?

**Comment by chenzhuo914** [comment]
Hi mitaky, have you started server (with "-startServer" argument") first?

Sorry to inform you, but we will be removing the server modules in v2 release, please refer to [this blog post](http://googleadsdeveloper.blogspot.com/2017/01/upcoming-changes-to-awreporting.html) for details and feedback.

That means, if you still want to use aw-reporting-server, you have to maintain it yourself in the future, otherwise please try to implement you own front-end logic to show the data from backend database (downloaded by aw-reporting module).

**Comment by chenzhuo914** [comment]
Closing for now, please feel free to reopen if necessary.
