### ISSUE TITLE
org.hibernate.NonUniqueObjectException

### ISSUE THREAD

**Issue by hakimio** [googleads/aw-reporting#268]
Following campaign performance report config causes "org.hibernate.NonUniqueObjectException":
CAMPAIGN_PERFORMANCE_REPORT=ExternalCustomerId,AccountDescriptiveName,CampaignName,Clicks,Impressions,Ctr,AverageCpc,Cost,AveragePosition,AllConversions,CostPerConversion,AllConversionValue,SearchBudgetLostImpressionShare

**Comment by chenzhuo914** [comment]
Hi hakimio, you should always select the ID field of report entity, for campaign performance report it's "CampaignId".

And, you would probably want to include "Date" field, otherwise it would be difficult to differentiate the time range of each report entry.

**Comment by hakimio** [comment]
Yes, adding "CampaignId" makes sense. It would be great if instead of crashing you would either automatically add that field or show an error message.
Having Date field doesn't make sense when you want to have aggregated data for the period.

**Comment by chenzhuo914** [comment]
The conflict only happens when there are multiple report entries without "CampaignId" field, so they cannot be persisted into SQL database due to duplicate identifier value. Please refer to the "setRowId()" method for the database identifier generation logic.

We don't want to enforce this restriction on AwReporting, because such report query is totally legitimate in AdWords API, and the result can be persisted to some storage that doesn't require such unique identifier.

**Comment by hakimio** [comment]
Still printing an error message instead of crashing would make sense...

**Comment by chenzhuo914** [comment]
From "NonUniqueObjectException" we can only say it's **possible** due to conflict of identifier of report entities during persistence, but we cannot say "CampaignId" is the culprit, because from [report types](https://developers.google.com/adwords/api/docs/appendix/reports) is the ID field of campaign performance report. (yep it sounds trivial, but the coding requires unambiguous data logic)

So at most it could just print some message like "possible identifier conflict, check your selected fields", do you feel it's much more useful than "NonUniqueObjectException"? And please feel free to propose code change if you have any good idea. :)

**Comment by hakimio** [comment]
Yes, I do think an error message like that would help a lot and you should exit immediately instead of trying to persist the rest of the records. I don't think it's really that obvious what might have caused that exception and when it crashes you get a huge output with all the stack traces for thousands of records which failed to persist. Not very user friendly...

**Comment by chenzhuo914** [comment]
My concern is that it's not 100% sure that NonUniqueObjectException is due to misconfig in selected fields (that's why I said "possible"); also, exit immediately would stop all other correctly configured report types (say, user also wants to download adgroup performance report) from being downloaded, which is a bit too harsh.

More importantly, we don't want to keep adding special handling of concrete runtime exceptions. Can we draw a clear line at which exceptions need special handling and which don't?

IMHO logging thousands of error records is not a big problem - as it effectively notifies user to fix the error. I admit it's not very user friendly, but I think it's a lesser evil.

**Comment by chenzhuo914** [comment]
After more thinking, I would propose that we implement a precheck feature, which detects potential issues on user selected report fields before actually downloading reports. Main problems are incompatible fields, fields not compatible with zero impressions, not including ID field of the entity, and too many segment fields. There will be an command line option to enable this precheck (default is off, so current users won't see behavior change).

**Comment by hakimio** [comment]
Sounds good. Feel free to close the issue once it's done.

**Comment by andrearaujol** [comment]
I'm trying to run a CampaignPerformanceReport using the following fields;
ExternalCustomerId,CampaignId,Date,HourOfDay,Device,AccountDescriptiveName,Cost,Clicks,Impressions,Conversions,ConversionValue,AveragePosition,AccountCurrencyCode,CampaignName,CampaignStatus

And I get the NonUnique error. When I remove the "HourOfDay" it works just fine. Does anyone have the same issue running reports that contain "HourOfDay" too?

**Comment by nwbirnie** [comment]
So fixing this will require a change to the primary key structure in the database. This will take a bit of time to get right. We need to be very careful with existing data to prevent duplicate rows being created. I'll update this issue in due course as we go through the design review, implementation and testing process. It will likely be 2018 before we have the capacity to handle this. In the meantime, if anyone is blocked due to this issue, please reach out and I'll be happy to provide guidance on a manual migration.

**Comment by hakimio** [comment]
@nwbirnie Might be worth reading what's this bug report is about before copy-pasting same answer from a different bug report...

**Comment by nwbirnie** [comment]
The plan is to address both bugs with the same fix, while improving the product overall by not requiring user intervention at the schema level. Currently fields are either not included in the primary key, or require the user to interpolate by hand based on error messages (which maybe rather cryptic as @chenzhuo914 points out.) 

We want a solution which works for the general case and makes the platform as a whole more robust and user-friendly :)

**Comment by nwbirnie** [comment]
Hi Mo,

Would you kindly reach out to me on email and we can discuss potential workaround here?

nwb@google.com

Best wishes,

Nick

**Comment by nwbirnie** [comment]
The latest release here includes a fix for this issue. The duplicate row error is trapped and it shows the suggested resolution (modify your report download query to add the missing fields.)
