### ISSUE TITLE
Add Postgres DB support

### ISSUE THREAD

**Issue by mrfleece** [googleads/aw-reporting#269]
Would it be possible to add Postgres support?

**Comment by chenzhuo914** [comment]
Sorry we don't have resource to support Postgres database type, mainly because it would involve much testing and maintenance.

In fact, the persistence module uses Java hibernate, which supports many database types including Postgres. Please look at aw-reporting/src/main/resources/data-source-mysql.xml to see the Hibernate configurations, and refer to [this article](http://jvmhub.com/2014/10/22/hibernate-and-postgresql-configuration-with-maven/) on how to configure Postgres instead.

**Comment by mrfleece** [comment]
I see, thanks! Keep up the good work!
