### ISSUE TITLE
Unsupported DateRange type: ALL_TIME

### ISSUE THREAD

**Issue by muhlegg** [googleads/aw-reporting#279]
Preparing our update to v201708 but receive a "Unsupported DateRange type: ALL_TIME"  message when trying to fetch all time data as we always have done. 

`java -Xmx1G -jar reportfetcher.jar -accountIdsFile test.txt -file test.properties -dateRange ALL_TIME`

The same command works with for example LAST_MONTH. 

Any ideas what this is caused by? What can we do? This i quite urgent since our current version stops working on 2.10.

The aw-reporting tool is from yesterday so the latest version.

**Comment by muhlegg** [comment]
Ok it does indeed seem like the ALL_TIME is not supported anymore at all. Must have missed that in the changelogs :/

**Comment by nwbirnie** [comment]
The ALL_TIME date range has not been supported since early 2016. It would appear that this was not communicated in the changelog, which would have been helpful in identifying compatibility issues sooner. I'll try to make sure that we get the release notes right going forwards.

In the meantime, you could parameterise the execution to specify a start which predates your campaigns and the end as today. For example on a linux machine, -startDate 2000-01-01 and -endDate $(date +%F).

**Comment by muhlegg** [comment]
Ok, thanks for the response. Cannot be early 2016 since our current version is v201609 and it works fine. 

Already working on a start- and enddate workaround. Feels a bit hacky though since we do fetch several different time spans so the ALL_TIME check was convenient when querying the data into our other applications. 

We'll just have to hope we get all the refactoring done in time before the v201609 sunset... :)

**Comment by muhlegg** [comment]
Just to be sure, why did you remove the ALL_TIME date range? Are there any indications it will be removed from the AdWords API? Asking because we are using it in our straight api calls as well.

**Comment by muhlegg** [comment]
And this $(date +%F) approach will create a new row for each day, not as the ALL_TIME that would replace the row keeping just one row with up-to-date all time data.
