### ISSUE TITLE
Super Threading

### ISSUE THREAD

**Issue by robtro** [googleads/aw-reporting#74]
Gents, 

I'm testing the tool on some servers with 64 cores, after tracing and looking at the processes in real time - it's hard to confirm that the process is actually multi-threading the DB insertion process. Is it? At best I've only seen 2-3 concurrent threads being opened. (Yes, mysql is configured for maximum innodb concurrency, and all other parameters configured properly)

**Comment by robtro** [comment]
Well, that's disappointing - why is this closed?

**Comment by gustavo-moreira** [comment]
Hi Rob,

we added this to our backlog to br considered in the future, but right now
our priority is the migration to the new version and aw-reporting server.
Also, we are revisiting the way we create PDFs since this is a feature that
impact a big number of users.
We will take a look into this again.

Cheers.

**Comment by litan1106** [comment]
I am also trying to figure out the best processor threads number and rows size for my Intel Xeon 8 cores
16 GB RAM (It's not using 100% cpu or memory)

aw.report.processor.rows.size=8000
aw.report.processor.threads=200
